name: generate

on:
  schedule:
    - cron: '1 14 * * *'    

jobs:
   build:
    name: Running generate
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run app
      run: go run cmd/main.go