name: generate

on:
  schedule:
    - cron: '30 16 * * *'
  push:
    branches:
      - 'main'
  pull_request:  

jobs:
   build:
    name: Running generate
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run app
      run: go run cmd/main.go
    - uses: actions/checkout@v2
    - name: Git push
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'github-actions@noreply.github.com'
        git rm -fr ./data/
        git commit -am "Automated build"
        git push
